In [1]:
import pandas as pd

In [4]:
data= pd.read_csv(r"G:\weatherHistory.csv")

In [5]:
data

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.
...,...,...,...,...,...,...,...,...,...,...,...,...
96448,2016-09-09 19:00:00.000 +0200,Partly Cloudy,rain,26.016667,26.016667,0.43,10.9963,31.0,16.1000,0.0,1014.36,Partly cloudy starting in the morning.
96449,2016-09-09 20:00:00.000 +0200,Partly Cloudy,rain,24.583333,24.583333,0.48,10.0947,20.0,15.5526,0.0,1015.16,Partly cloudy starting in the morning.
96450,2016-09-09 21:00:00.000 +0200,Partly Cloudy,rain,22.038889,22.038889,0.56,8.9838,30.0,16.1000,0.0,1015.66,Partly cloudy starting in the morning.
96451,2016-09-09 22:00:00.000 +0200,Partly Cloudy,rain,21.522222,21.522222,0.60,10.5294,20.0,16.1000,0.0,1015.95,Partly cloudy starting in the morning.
96452,2016-09-09 23:00:00.000 +0200,Partly Cloudy,rain,20.438889,20.438889,0.61,5.8765,39.0,15.5204,0.0,1016.16,Partly cloudy starting in the morning.

In [6]:
data.head()

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.

In [8]:
data.shape

(96453, 12)

In [11]:
data.index

RangeIndex(start=0, stop=96453, step=1)

In [12]:
data.columns

Index(['Formatted Date', 'Summary', 'Precip Type', 'Temperature (C)',
       'Apparent Temperature (C)', 'Humidity', 'Wind Speed (km/h)',
       'Wind Bearing (degrees)', 'Visibility (km)', 'Loud Cover',
       'Pressure (millibars)', 'Daily Summary'],
      dtype='object')

In [13]:
data.dtypes

Formatted Date               object
Summary                      object
Precip Type                  object
Temperature (C)             float64
Apparent Temperature (C)    float64
Humidity                    float64
Wind Speed (km/h)           float64
Wind Bearing (degrees)      float64
Visibility (km)             float64
Loud Cover                  float64
Pressure (millibars)        float64
Daily Summary                object
dtype: object

In [14]:
data['Humidity'].unique()

array([0.89, 0.86, 0.83, 0.85, 0.95, 0.82, 0.72, 0.67, 0.54, 0.55, 0.51,
       0.47, 0.46, 0.6 , 0.63, 0.69, 0.7 , 0.77, 0.76, 0.79, 0.62, 0.66,
       0.8 , 0.78, 0.61, 0.52, 0.4 , 0.37, 0.36, 0.43, 0.5 , 0.53, 0.58,
       0.59, 0.87, 0.93, 0.84, 0.73, 0.71, 0.74, 0.81, 0.9 , 0.99, 0.96,
       0.75, 0.88, 0.65, 0.91, 0.94, 0.92, 0.44, 0.56, 0.68, 0.64, 0.48,
       0.57, 0.98, 1.  , 0.38, 0.41, 0.45, 0.49, 0.32, 0.42, 0.35, 0.39,
       0.97, 0.34, 0.33, 0.31, 0.3 , 0.29, 0.27, 0.28, 0.26, 0.24, 0.25,
       0.23, 0.19, 0.17, 0.2 , 0.15, 0.18, 0.22, 0.14, 0.21, 0.16, 0.13,
       0.  , 0.12])

In [15]:
data.nunique()

Formatted Date              96429
Summary                        27
Precip Type                     2
Temperature (C)              7574
Apparent Temperature (C)     8984
Humidity                       90
Wind Speed (km/h)            2484
Wind Bearing (degrees)        360
Visibility (km)               949
Loud Cover                      1
Pressure (millibars)         4979
Daily Summary                 214
dtype: int64

In [16]:
data.count()

Formatted Date              96453
Summary                     96453
Precip Type                 95936
Temperature (C)             96453
Apparent Temperature (C)    96453
Humidity                    96453
Wind Speed (km/h)           96453
Wind Bearing (degrees)      96453
Visibility (km)             96453
Loud Cover                  96453
Pressure (millibars)        96453
Daily Summary               96453
dtype: int64

In [17]:
data['Precip Type'].value_counts()

rain    85224
snow    10712
Name: Precip Type, dtype: int64

In [18]:
data['Precip Type'].unique()

array(['rain', 'snow', nan], dtype=object)

In [19]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96453 entries, 0 to 96452
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Formatted Date            96453 non-null  object
 1   Summary                   96453 non-null  object
 2   Precip Type               95936 non-null  object
 3   Temperature (C)           96453 non-null  float64
 4   Apparent Temperature (C)  96453 non-null  float64
 5   Humidity                  96453 non-null  float64
 6   Wind Speed (km/h)         96453 non-null  float64
 7   Wind Bearing (degrees)    96453 non-null  float64
 8   Visibility (km)           96453 non-null  float64
 9   Loud Cover                96453 non-null  float64
 10  Pressure (millibars)      96453 non-null  float64
 11  Daily Summary             96453 non-null  object
dtypes: float64(8), object(4)
memory usage: 8.8+ MB

In [20]:
data.head(1)

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.

In [21]:
data.nunique()

Formatted Date              96429
Summary                        27
Precip Type                     2
Temperature (C)              7574
Apparent Temperature (C)     8984
Humidity                       90
Wind Speed (km/h)            2484
Wind Bearing (degrees)        360
Visibility (km)               949
Loud Cover                      1
Pressure (millibars)         4979
Daily Summary                 214
dtype: int64

In [23]:
data['Wind Speed (km/h)'].nunique()

2484

In [24]:
data['Wind Speed (km/h)'].unique()

array([14.1197, 14.2646,  3.9284, ..., 37.0622, 35.5971, 30.751 ])

In [25]:
data.head(1)

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.

In [26]:
data['Daily Summary'].unique()

array(['Partly cloudy throughout the day.',
       'Mostly cloudy throughout the day.', 'Foggy in the evening.',
       'Foggy overnight and breezy in the morning.',
       'Overcast throughout the day.', 'Partly cloudy until night.',
       'Mostly cloudy until night.',
       'Foggy starting overnight continuing until morning.',
       'Foggy in the morning.', 'Partly cloudy until evening.',
       'Partly cloudy starting in the morning.',
       'Mostly cloudy starting overnight continuing until night.',
       'Mostly cloudy until evening.',
       'Partly cloudy starting in the morning continuing until evening.',
       'Partly cloudy starting in the afternoon.',
       'Partly cloudy starting overnight.',
       'Partly cloudy until morning.',
       'Partly cloudy starting overnight continuing until night.',
       'Partly cloudy starting in the afternoon continuing until night.',
       'Mostly cloudy starting overnight.',
       'Partly cloudy until afternoon.',
       'Mostly cloudy until night and breezy in the afternoon.',
       'Foggy starting in the evening.', 'Foggy throughout the day.',
       'Foggy starting in the evening continuing until night.',
       'Mostly cloudy until morning.',
       'Foggy starting in the morning continuing until evening.',
       'Foggy starting overnight continuing until afternoon.',
       'Partly cloudy starting in the morning continuing until afternoon.',
       'Foggy starting overnight.', 'Foggy until morning.',
       'Foggy starting overnight continuing until evening.',
       'Foggy starting in the afternoon.',
       'Partly cloudy starting overnight continuing until afternoon.',
       'Partly cloudy starting in the morning continuing until night.',
       'Overcast until night.',
       'Mostly cloudy starting overnight continuing until evening.',
       'Foggy overnight.', 'Partly cloudy in the morning.',
       'Mostly cloudy starting in the morning.',
       'Foggy starting in the afternoon continuing until evening.',
       'Mostly cloudy until afternoon.',
       'Foggy starting overnight continuing until night.',
       'Mostly cloudy throughout the day and breezy in the evening.',
       'Foggy starting in the morning continuing until afternoon.',
       'Partly cloudy in the afternoon.', 'Clear throughout the day.',
       'Partly cloudy starting in the afternoon continuing until evening.',
       'Partly cloudy overnight.', 'Overcast until evening.',
       'Foggy in the morning and breezy starting in the afternoon continuing until night.',
       'Breezy starting overnight continuing until afternoon and foggy starting in the morning continuing until evening.',
       'Partly cloudy starting overnight continuing until morning.',
       'Mostly cloudy throughout the day and breezy in the afternoon.',
       'Mostly cloudy starting overnight and breezy in the afternoon.',
       'Partly cloudy throughout the day and breezy starting in the morning continuing until night.',
       'Mostly cloudy throughout the day and breezy in the morning.',
       'Partly cloudy starting in the evening continuing until night.',
       'Mostly cloudy until night and breezy starting in the morning continuing until afternoon.',
       'Partly cloudy starting in the morning continuing until evening and breezy starting in the morning continuing until afternoon.',
       'Partly cloudy throughout the day and breezy starting in the morning continuing until afternoon.',
       'Partly cloudy throughout the day and breezy starting in the morning continuing until evening.',
       'Foggy until afternoon.',
       'Overcast until night and breezy overnight.',
       'Breezy until morning and mostly cloudy throughout the day.',
       'Mostly cloudy starting in the morning continuing until night.',
       'Breezy starting overnight continuing until morning and partly cloudy starting overnight continuing until evening.',
       'Partly cloudy in the evening.',
       'Mostly cloudy starting overnight continuing until afternoon.',
       'Mostly cloudy starting in the morning continuing until afternoon.',
       'Mostly cloudy starting in the afternoon.',
       'Mostly cloudy starting in the morning continuing until evening.',
       'Partly cloudy starting overnight continuing until afternoon and breezy in the afternoon.',
       'Partly cloudy starting overnight and breezy in the afternoon.',
       'Mostly cloudy starting in the morning and breezy in the evening.',
       'Foggy starting in the afternoon continuing until night.',
       'Foggy until night.',
       'Foggy starting in the morning continuing until night.',
       'Foggy until evening.', 'Foggy starting in the morning.',
       'Partly cloudy starting overnight continuing until evening.',
       'Partly cloudy starting overnight continuing until evening and breezy starting in the morning continuing until evening.',
       'Breezy starting overnight continuing until morning and foggy in the evening.',
       'Mostly cloudy throughout the day and breezy starting in the morning continuing until evening.',
       'Partly cloudy until evening and breezy starting in the morning continuing until afternoon.',
       'Mostly cloudy starting in the afternoon continuing until night.',
       'Breezy starting overnight continuing until afternoon and mostly cloudy starting overnight continuing until evening.',
       'Mostly cloudy throughout the day and windy starting in the morning continuing until evening.',
       'Breezy and partly cloudy in the afternoon.',
       'Mostly cloudy starting overnight and breezy starting in the morning continuing until afternoon.',
       'Partly cloudy until night and breezy starting in the morning continuing until afternoon.',
       'Breezy and mostly cloudy overnight.',
       'Mostly cloudy throughout the day and breezy overnight.',
       'Mostly cloudy throughout the day and breezy starting in the morning continuing until afternoon.',
       'Partly cloudy throughout the day and breezy in the morning.',
       'Partly cloudy starting in the morning continuing until evening and breezy starting in the afternoon continuing until evening.',
       'Partly cloudy throughout the day and breezy starting in the afternoon continuing until evening.',
       'Mostly cloudy starting overnight and breezy in the morning.',
       'Partly cloudy starting in the afternoon and breezy in the afternoon.',
       'Partly cloudy starting in the morning and breezy in the evening.',
       'Partly cloudy until evening and breezy in the morning.',
       'Partly cloudy starting overnight continuing until evening and breezy starting in the morning continuing until afternoon.',
       'Partly cloudy starting overnight continuing until evening and breezy in the evening.',
       'Mostly cloudy throughout the day and breezy starting in the evening.',
       'Mostly cloudy throughout the day and windy starting in the morning continuing until night.',
       'Breezy starting overnight continuing until morning and partly cloudy starting in the morning.',
       'Mostly cloudy starting in the morning and breezy overnight.',
       'Overcast throughout the day and breezy starting overnight continuing until morning.',
       'Partly cloudy throughout the day and breezy in the evening.',
       'Mostly cloudy until evening and breezy starting in the morning continuing until afternoon.',
       'Mostly cloudy until night and breezy in the evening.',
       'Partly cloudy starting in the evening.',
       'Overcast starting in the morning.',
       'Mostly cloudy starting overnight continuing until evening and breezy starting overnight continuing until morning.',
       'Partly cloudy starting overnight continuing until morning and breezy starting in the morning continuing until afternoon.',
       'Partly cloudy until evening and breezy starting in the morning continuing until evening.',
       'Breezy starting in the morning continuing until afternoon and partly cloudy starting in the morning.',
       'Partly cloudy starting in the morning and breezy starting in the afternoon continuing until evening.',
       'Mostly cloudy starting overnight continuing until morning.',
       'Mostly cloudy throughout the day and breezy starting overnight continuing until afternoon.',
       'Breezy starting overnight continuing until morning and foggy overnight.',
       'Mostly cloudy throughout the day and breezy starting overnight continuing until morning.',
       'Overcast throughout the day and breezy in the morning.',
       'Overcast throughout the day and breezy in the evening.',
       'Mostly cloudy starting in the morning continuing until night and breezy in the afternoon.',
       'Mostly cloudy until night and breezy starting in the evening continuing until night.',
       'Partly cloudy until night and breezy in the morning.',
       'Partly cloudy until evening and breezy overnight.',
       'Partly cloudy starting overnight continuing until night and windy starting in the morning continuing until afternoon.',
       'Breezy starting in the morning continuing until afternoon and mostly cloudy starting in the morning.',
       'Foggy starting overnight continuing until morning and breezy starting in the evening.',
       'Mostly cloudy until night and breezy starting in the afternoon.',
       'Foggy in the afternoon.',
       'Mostly cloudy until night and breezy starting in the afternoon continuing until night.',
       'Foggy starting overnight continuing until morning and breezy starting in the evening continuing until night.',
       'Breezy until afternoon and mostly cloudy throughout the day.',
       'Mostly cloudy throughout the day and breezy starting in the morning continuing until night.',
       'Partly cloudy starting overnight continuing until evening and breezy in the morning.',
       'Mostly cloudy starting in the morning and breezy in the afternoon.',
       'Mostly cloudy starting overnight continuing until night and breezy starting in the morning continuing until evening.',
       'Foggy starting overnight continuing until morning and breezy starting in the morning continuing until afternoon.',
       'Mostly cloudy until evening and windy starting in the morning continuing until afternoon.',
       'Foggy starting overnight continuing until afternoon and breezy in the morning.',
       'Foggy starting in the morning continuing until afternoon and breezy starting in the evening.',
       'Partly cloudy starting overnight and breezy starting in the morning continuing until afternoon.',
       'Foggy starting overnight continuing until morning and breezy in the afternoon.',
       'Mostly cloudy starting overnight and breezy starting in the afternoon continuing until evening.',
       'Overcast throughout the day and breezy starting overnight continuing until afternoon.',
       'Partly cloudy starting in the morning continuing until evening and breezy in the afternoon.',
       'Partly cloudy starting in the morning continuing until night and breezy starting in the afternoon continuing until evening.',
       'Mostly cloudy until night and breezy starting in the evening.',
       'Breezy in the morning and mostly cloudy starting in the morning.',
       'Mostly cloudy until night and breezy starting in the morning continuing until evening.',
       'Partly cloudy starting overnight continuing until evening and windy starting in the morning continuing until evening.',
       'Breezy in the morning and partly cloudy starting in the evening continuing until night.',
       'Partly cloudy overnight and breezy starting in the morning continuing until afternoon.',
       'Light rain in the morning.', 'Light rain until morning.',
       'Light rain in the morning and afternoon.',
       'Partly cloudy starting in the morning continuing until night and breezy starting in the morning continuing until afternoon.',
       'Breezy starting in the afternoon continuing until night and mostly cloudy starting in the evening.',
       'Mostly cloudy throughout the day and breezy starting in the evening continuing until night.',
       'Foggy starting in the afternoon and breezy starting in the afternoon continuing until evening.',
       'Breezy and foggy until morning.',
       'Mostly cloudy until night and breezy starting overnight continuing until morning.',
       'Partly cloudy starting overnight continuing until night and breezy in the morning.',
       'Partly cloudy starting overnight continuing until night and breezy in the afternoon.',
       'Mostly cloudy starting in the morning and breezy starting in the afternoon continuing until evening.',
       'Partly cloudy starting overnight and breezy starting in the evening.',
       'Breezy overnight and overcast throughout the day.',
       'Partly cloudy until night and breezy in the afternoon.',
       'Mostly cloudy starting overnight and breezy starting in the evening.',
       'Breezy overnight and partly cloudy until evening.',
       'Mostly cloudy starting in the evening.',
       'Mostly cloudy throughout the day and breezy starting in the afternoon.',
       'Mostly cloudy throughout the day and breezy starting in the afternoon continuing until evening.',
       'Mostly cloudy until night and windy starting in the morning continuing until afternoon.',
       'Breezy and foggy starting in the evening.',
       'Breezy overnight and partly cloudy throughout the day.',
       'Overcast throughout the day and breezy starting in the evening.',
       'Breezy until evening and foggy in the morning.',
       'Breezy overnight and mostly cloudy throughout the day.',
       'Partly cloudy until evening and breezy in the afternoon.',
       'Partly cloudy starting in the morning and breezy starting in the morning continuing until afternoon.',
       'Mostly cloudy until evening and breezy in the evening.',
       'Windy in the afternoon.', 'Overcast until morning.',
       'Mostly cloudy overnight.',
       'Foggy starting in the morning continuing until evening and breezy in the evening.',
       'Breezy starting overnight continuing until morning.',
       'Breezy starting in the afternoon continuing until evening and foggy starting in the evening.',
       'Mostly cloudy until night and breezy overnight.',
       'Mostly cloudy starting in the morning and windy in the evening.',
       'Partly cloudy throughout the day and windy starting in the morning continuing until afternoon.',
       'Breezy until afternoon and overcast throughout the day.',
       'Breezy in the morning and foggy in the evening.',
       'Breezy starting in the afternoon continuing until evening and foggy in the evening.',
       'Breezy starting in the morning continuing until night.',
       'Breezy in the morning and mostly cloudy starting in the evening.',
       'Mostly cloudy until evening and breezy in the afternoon.',
       'Mostly cloudy until night and breezy starting in the afternoon continuing until evening.',
       'Mostly cloudy until evening and breezy starting overnight continuing until morning.',
       'Overcast throughout the day and breezy in the afternoon.',
       'Overcast throughout the day and breezy starting in the morning continuing until evening.',
       'Overcast throughout the day and breezy overnight.',
       'Overcast starting in the afternoon.',
       'Partly cloudy throughout the day and breezy in the afternoon.',
       'Light rain starting overnight.',
       'Drizzle starting in the evening.', 'Drizzle until morning.',
       'Rain throughout the day.', 'Rain until morning.',
       'Light rain overnight.', 'Rain until afternoon.'], dtype=object)

In [28]:
data['Daily Summary'].value_counts()

Mostly cloudy throughout the day.                                                                                   20085
Partly cloudy throughout the day.                                                                                    9981
Partly cloudy until night.                                                                                           6169
Partly cloudy starting in the morning.                                                                               5184
Foggy in the morning.                                                                                                4201
                                                                                                                    ...
Mostly cloudy throughout the day and breezy starting in the evening continuing until night.                            24
Breezy starting overnight continuing until afternoon and foggy starting in the morning continuing until evening.       24
Breezy in the morning and foggy in the evening.                                                                        24
Overcast starting in the morning.                                                                                      24
Foggy starting overnight continuing until morning and breezy in the afternoon.                                         23
Name: Daily Summary, Length: 214, dtype: int64

In [43]:
#filtering
data[data['Daily Summary'] ==  'Mostly cloudy throughout the day']

Empty DataFrame
Columns: [Formatted Date, Summary, Precip Type, Temperature (C), Apparent Temperature (C), Humidity, Wind Speed (km/h), Wind Bearing (degrees), Visibility (km), Loud Cover, Pressure (millibars), Daily Summary]
Index: []

In [44]:
data.head(1)

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.

In [52]:
data.head(1)

AttributeError: 'list' object has no attribute 'head'

In [53]:
data.head()

AttributeError: 'list' object has no attribute 'head'

In [1]:
data.head()

NameError: name 'data' is not defined

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv(r"G:\weatherHistory.csv")

In [3]:
df

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.
...,...,...,...,...,...,...,...,...,...,...,...,...
96448,2016-09-09 19:00:00.000 +0200,Partly Cloudy,rain,26.016667,26.016667,0.43,10.9963,31.0,16.1000,0.0,1014.36,Partly cloudy starting in the morning.
96449,2016-09-09 20:00:00.000 +0200,Partly Cloudy,rain,24.583333,24.583333,0.48,10.0947,20.0,15.5526,0.0,1015.16,Partly cloudy starting in the morning.
96450,2016-09-09 21:00:00.000 +0200,Partly Cloudy,rain,22.038889,22.038889,0.56,8.9838,30.0,16.1000,0.0,1015.66,Partly cloudy starting in the morning.
96451,2016-09-09 22:00:00.000 +0200,Partly Cloudy,rain,21.522222,21.522222,0.60,10.5294,20.0,16.1000,0.0,1015.95,Partly cloudy starting in the morning.
96452,2016-09-09 23:00:00.000 +0200,Partly Cloudy,rain,20.438889,20.438889,0.61,5.8765,39.0,15.5204,0.0,1016.16,Partly cloudy starting in the morning.

In [4]:
df.head(2)

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.

In [5]:
df.Daily Summary.value_counts()

SyntaxError: invalid syntax (<ipython-input-5-0171336f2145>, line 1)

In [6]:
df['Daily Summary'].value_counts()

Mostly cloudy throughout the day.                                                                  20085
Partly cloudy throughout the day.                                                                   9981
Partly cloudy until night.                                                                          6169
Partly cloudy starting in the morning.                                                              5184
Foggy in the morning.                                                                               4201
                                                                                                   ...
Mostly cloudy overnight.                                                                              24
Mostly cloudy starting overnight and breezy starting in the afternoon continuing until evening.       24
Drizzle until morning.                                                                                24
Foggy starting overnight continuing until afternoon and breezy in the morning.                        24
Foggy starting overnight continuing until morning and breezy in the afternoon.                        23
Name: Daily Summary, Length: 214, dtype: int64

In [7]:
df['Daily Summary'] == "Foggy in the morning"

0        False
1        False
2        False
3        False
4        False
         ...
96448    False
96449    False
96450    False
96451    False
96452    False
Name: Daily Summary, Length: 96453, dtype: bool

In [8]:
df[df.Daily Summary == " Foggy in the mormning"]

SyntaxError: invalid syntax (<ipython-input-8-db32e7312a64>, line 1)

In [9]:
data= df[df['Daily Summary'] = Foggy in the morning]

SyntaxError: invalid syntax (<ipython-input-9-c057ca640da5>, line 1)

In [10]:

# selecting rows based on condition  
rslt_df = df.loc[df['Daily Summary'] = Foggy in the morning]

SyntaxError: invalid syntax (<ipython-input-10-088f396064eb>, line 2)

In [11]:
rslt_df = df.loc[df['Daily Summary'] == Foggy in the morning]

SyntaxError: invalid syntax (<ipython-input-11-71415fb9f2c8>, line 1)

In [12]:
rslt_df = df.loc[df['Daily Summary'] = Foggy]

SyntaxError: invalid syntax (<ipython-input-12-6a23560c65e6>, line 1)

In [13]:
df.head(2)

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.

In [14]:
res=df[df['Temperature']> 9.3]

KeyError: 'Temperature'

In [15]:
res

NameError: name 'res' is not defined

In [16]:
res=df[df['Temperature']> 9.355556]

KeyError: 'Temperature'

In [17]:
df.head(1)

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.

In [24]:
result = df.loc[df['Wind Bearing (degrees)'] > 251.0]

In [25]:
result

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.
5,2006-04-01 05:00:00.000 +0200,Partly Cloudy,rain,9.222222,7.111111,0.85,13.9587,258.0,14.9569,0.0,1016.66,Partly cloudy throughout the day.
6,2006-04-01 06:00:00.000 +0200,Partly Cloudy,rain,7.733333,5.522222,0.95,12.3648,259.0,9.9820,0.0,1016.72,Partly cloudy throughout the day.
...,...,...,...,...,...,...,...,...,...,...,...,...
96426,2016-09-08 21:00:00.000 +0200,Mostly Cloudy,rain,21.016667,21.016667,0.64,3.2200,340.0,16.1000,0.0,1014.73,Partly cloudy starting overnight.
96427,2016-09-08 22:00:00.000 +0200,Partly Cloudy,rain,19.927778,19.927778,0.71,3.1556,302.0,16.1000,0.0,1014.63,Partly cloudy starting overnight.
96430,2016-09-09 01:00:00.000 +0200,Clear,rain,16.622222,16.622222,0.87,3.4293,349.0,16.1000,0.0,1014.56,Partly cloudy starting in the morning.
96433,2016-09-09 04:00:00.000 +0200,Clear,rain,15.011111,15.011111,0.93,3.2039,341.0,15.8263,0.0,1014.37,Partly cloudy starting in the morning.
96434,2016-09-09 05:00:00.000 +0200,Clear,rain,15.016667,15.016667,0.90,2.7048,359.0,14.9569,0.0,1014.55,Partly cloudy starting in the morning.

In [27]:
result = df.loc[df['Daily Summary'] ==  'Partly cloudy throughout the day.']

In [28]:
result

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.
...,...,...,...,...,...,...,...,...,...,...,...,...
96400,2016-09-07 19:00:00.000 +0200,Partly Cloudy,rain,23.838889,23.838889,0.62,3.2200,70.0,16.1000,0.0,1018.95,Partly cloudy throughout the day.
96401,2016-09-07 20:00:00.000 +0200,Partly Cloudy,rain,21.005556,21.005556,0.73,0.3220,10.0,15.5526,0.0,1019.43,Partly cloudy throughout the day.
96402,2016-09-07 21:00:00.000 +0200,Partly Cloudy,rain,19.838889,19.838889,0.79,3.2200,40.0,16.1000,0.0,1019.83,Partly cloudy throughout the day.
96403,2016-09-07 22:00:00.000 +0200,Partly Cloudy,rain,18.727778,18.727778,0.84,0.0000,0.0,16.1000,0.0,1019.64,Partly cloudy throughout the day.
96404,2016-09-07 23:00:00.000 +0200,Partly Cloudy,rain,17.661111,17.661111,0.88,3.2200,10.0,15.1501,0.0,1019.39,Partly cloudy throughout the day.

In [1]:
def hello():
    print("jkssdbjc")

In [2]:
hello()

jkssdbjc

In [3]:
def hello(name):
    print('howdy' + name)
hello('veer')

howdyveer

In [9]:
import random
def numbers(enter):
    if enter == 1:
        return 'hi'
    elif enter ==2:
        return 'hii'
    elif enter == 3:
        return 'hiii'
r=random.randint(1,3)
numbers(r)

'hi'

In [12]:
print('a','b', sep='+')
print('c')

a+b
c

In [14]:
def spam():
    eggs=100
    bacon()
    print(eggs)
    
def bacon():
    value=101
    eggs=0
    print(value)

spam()

101
100

In [15]:
#numpy

import numpy as np
n1=np.array([1,2,3,4])
#n1 is a object
n1

array([1, 2, 3, 4])

In [19]:
import numpy as np
n2=np.array([[1,2,3,4],[3,4,5,4]])
n2

array([[1, 2, 3, 4],
       [3, 4, 5, 4]])

In [21]:
import numpy as np
n1=np.zeros((2,3))
n1

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
n2=np.full((1,3),7)
n2

array([[7, 7, 7]])

In [23]:
#initialize with a range

n3=np.arange(2,9)
n3

array([2, 3, 4, 5, 6, 7, 8])

In [24]:
#skip value
n3=np.arange(2,100,10)
n3

array([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92])

In [30]:
#range of 1 to 100  with 5 random
import numpy as np
n4=np.random.randint(1,100,5)
n4

array([97,  5, 58, 71, 66])

In [39]:
n3=np.zeros((5,2))
n3

n3.shape=

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [46]:
#stacking methods
#vertical, horizontal,column
#dont miss brackets for multi dimension array it gives u type error with field elements must be 2 or 3 tupls

n5=np.array([[1,2,3],[1,2,4]])
n6=np.array([1,23,4])
np.vstack((n5,n6))

np.column_stack((n5,n6))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 3

In [50]:

#for common elements intersect1d, for unique setdiff1d 

import numpy as np
n1=np.array([1,2,3])
n2=np.array([2,4,6])
np.intersect1d(n1,n2)
np.setdiff1d(n1,n2) #unique in n1

TypeError: _setdiff1d_dispatcher() missing 1 required positional argument: 'ar2'

In [2]:
 #ADDITION ON NUMPY
    
#sum method
# sum along column axis=0. row axis=1
import numpy as np
 n1=np.array([1,2])
n2=np.array([2,4])
np.sum([n1,n2],axis=0)

array([3, 6])

In [1]:
#basic scalar operations for individual elements in an array
#n1=n1-1,n1=n1+2
#mean , median, standard deviation methods

#transpose
#n1.dot(n2) for dot profduvt

#saving an array use save method and koad for loading
#np.save('name',n1)
import pandas as pd
data= pd.read_csv(r"G:\weatherHistory.csv")

In [2]:
data

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.
...,...,...,...,...,...,...,...,...,...,...,...,...
96448,2016-09-09 19:00:00.000 +0200,Partly Cloudy,rain,26.016667,26.016667,0.43,10.9963,31.0,16.1000,0.0,1014.36,Partly cloudy starting in the morning.
96449,2016-09-09 20:00:00.000 +0200,Partly Cloudy,rain,24.583333,24.583333,0.48,10.0947,20.0,15.5526,0.0,1015.16,Partly cloudy starting in the morning.
96450,2016-09-09 21:00:00.000 +0200,Partly Cloudy,rain,22.038889,22.038889,0.56,8.9838,30.0,16.1000,0.0,1015.66,Partly cloudy starting in the morning.
96451,2016-09-09 22:00:00.000 +0200,Partly Cloudy,rain,21.522222,21.522222,0.60,10.5294,20.0,16.1000,0.0,1015.95,Partly cloudy starting in the morning.
96452,2016-09-09 23:00:00.000 +0200,Partly Cloudy,rain,20.438889,20.438889,0.61,5.8765,39.0,15.5204,0.0,1016.16,Partly cloudy starting in the morning.

In [3]:
data.head(2)

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.

In [5]:
dt=data[groupby(' Daily Summary').get_group('Partly cloudy throughout the day.')

KeyError: ' Daily Summary'

In [6]:
data.query('Daily Summary == "Partly cloudy throughout the day."')

SyntaxError: invalid syntax (<unknown>, line 1)

In [7]:
data.head(2)

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.

In [8]:
#wind spped 14 above
data[data['Wind Speed (km/h)'] > 14]

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
7,2006-04-01 07:00:00.000 +0200,Partly Cloudy,rain,8.772222,6.527778,0.89,14.1519,260.0,9.9820,0.0,1016.84,Partly cloudy throughout the day.
10,2006-04-01 10:00:00.000 +0200,Partly Cloudy,rain,16.016667,16.016667,0.67,17.5651,290.0,11.2056,0.0,1017.42,Partly cloudy throughout the day.
...,...,...,...,...,...,...,...,...,...,...,...,...
96420,2016-09-08 15:00:00.000 +0200,Partly Cloudy,rain,29.950000,28.405556,0.25,21.8155,160.0,16.1000,0.0,1015.23,Partly cloudy starting overnight.
96442,2016-09-09 13:00:00.000 +0200,Partly Cloudy,rain,30.994444,29.972222,0.33,15.6170,70.0,16.1000,0.0,1014.86,Partly cloudy starting in the morning.
96443,2016-09-09 14:00:00.000 +0200,Partly Cloudy,rain,30.894444,29.450000,0.28,14.7798,43.0,15.5526,0.0,1014.66,Partly cloudy starting in the morning.
96444,2016-09-09 15:00:00.000 +0200,Partly Cloudy,rain,31.083333,29.616667,0.28,15.5043,40.0,16.1000,0.0,1014.17,Partly cloudy starting in the morning.
96446,2016-09-09 17:00:00.000 +0200,Partly Cloudy,rain,30.766667,29.311111,0.28,14.2163,24.0,15.5526,0.0,1013.83,Partly cloudy starting in the morning.

In [9]:
data[data['Daily Summary']== 'Partly cloudy starting in the morning.']

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
408,2006-04-25 00:00:00.000 +0200,Clear,rain,12.711111,12.711111,0.89,3.2522,169.0,15.8263,0.0,1020.11,Partly cloudy starting in the morning.
409,2006-04-25 01:00:00.000 +0200,Clear,rain,12.127778,12.127778,0.89,3.1717,148.0,14.9086,0.0,1020.12,Partly cloudy starting in the morning.
410,2006-04-25 02:00:00.000 +0200,Clear,rain,11.811111,11.811111,0.84,4.9910,68.0,14.9569,0.0,1018.38,Partly cloudy starting in the morning.
411,2006-04-25 03:00:00.000 +0200,Clear,rain,12.016667,12.016667,0.80,6.2629,169.0,14.9086,0.0,1019.91,Partly cloudy starting in the morning.
412,2006-04-25 04:00:00.000 +0200,Clear,rain,12.044444,12.044444,0.80,6.4239,187.0,14.8120,0.0,1020.03,Partly cloudy starting in the morning.
...,...,...,...,...,...,...,...,...,...,...,...,...
96448,2016-09-09 19:00:00.000 +0200,Partly Cloudy,rain,26.016667,26.016667,0.43,10.9963,31.0,16.1000,0.0,1014.36,Partly cloudy starting in the morning.
96449,2016-09-09 20:00:00.000 +0200,Partly Cloudy,rain,24.583333,24.583333,0.48,10.0947,20.0,15.5526,0.0,1015.16,Partly cloudy starting in the morning.
96450,2016-09-09 21:00:00.000 +0200,Partly Cloudy,rain,22.038889,22.038889,0.56,8.9838,30.0,16.1000,0.0,1015.66,Partly cloudy starting in the morning.
96451,2016-09-09 22:00:00.000 +0200,Partly Cloudy,rain,21.522222,21.522222,0.60,10.5294,20.0,16.1000,0.0,1015.95,Partly cloudy starting in the morning.
96452,2016-09-09 23:00:00.000 +0200,Partly Cloudy,rain,20.438889,20.438889,0.61,5.8765,39.0,15.5204,0.0,1016.16,Partly cloudy starting in the morning.

In [11]:
#finding null values 
#isnull
data.isnull() #boolean values
data.isnull().sum()

Formatted Date                0
Summary                       0
Precip Type                 517
Temperature (C)               0
Apparent Temperature (C)      0
Humidity                      0
Wind Speed (km/h)             0
Wind Bearing (degrees)        0
Visibility (km)               0
Loud Cover                    0
Pressure (millibars)          0
Daily Summary                 0
dtype: int64

In [12]:
data.notnull().sum()

Formatted Date              96453
Summary                     96453
Precip Type                 95936
Temperature (C)             96453
Apparent Temperature (C)    96453
Humidity                    96453
Wind Speed (km/h)           96453
Wind Bearing (degrees)      96453
Visibility (km)             96453
Loud Cover                  96453
Pressure (millibars)        96453
Daily Summary               96453
dtype: int64

In [13]:
data.notnull()

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,True,True,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...
96448,True,True,True,True,True,True,True,True,True,True,True,True
96449,True,True,True,True,True,True,True,True,True,True,True,True
96450,True,True,True,True,True,True,True,True,True,True,True,True
96451,True,True,True,True,True,True,True,True,True,True,True,True
96452,True,True,True,True,True,True,True,True,True,True,True,True

In [14]:
data.isnull()

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
96448,False,False,False,False,False,False,False,False,False,False,False,False
96449,False,False,False,False,False,False,False,False,False,False,False,False
96450,False,False,False,False,False,False,False,False,False,False,False,False
96451,False,False,False,False,False,False,False,False,False,False,False,False
96452,False,False,False,False,False,False,False,False,False,False,False,False

In [17]:
data.isnull('Precip Type')

TypeError: isnull() takes 1 positional argument but 2 were given

In [18]:
pd.isnull(data['Precip Type'])

0        False
1        False
2        False
3        False
4        False
         ...
96448    False
96449    False
96450    False
96451    False
96452    False
Name: Precip Type, Length: 96453, dtype: bool

In [19]:
data.sample(frac=0.30)

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
84263,2015-03-02 02:00:00.000 +0100,Mostly Cloudy,rain,4.327778,1.705556,0.96,10.7870,180.0,4.0250,0.0,1013.47,Mostly cloudy throughout the day and breezy in...
66744,2013-03-02 00:00:00.000 +0100,Mostly Cloudy,rain,2.777778,-0.255556,0.84,11.2056,290.0,10.0464,0.0,1018.14,Partly cloudy until night.
10768,2007-12-29 16:00:00.000 +0100,Foggy,snow,-5.027778,-9.072222,0.93,9.2897,144.0,2.1091,0.0,1032.92,Foggy starting in the morning.
27659,2009-08-04 11:00:00.000 +0200,Overcast,rain,25.866667,25.866667,0.59,10.4489,176.0,10.3684,0.0,1011.53,Mostly cloudy starting in the morning.
62467,2013-08-22 19:00:00.000 +0200,Mostly Cloudy,rain,24.972222,24.972222,0.50,9.1126,350.0,16.1000,0.0,1016.34,Partly cloudy throughout the day.
...,...,...,...,...,...,...,...,...,...,...,...,...
38004,2010-01-10 12:00:00.000 +0100,Mostly Cloudy,rain,6.927778,6.927778,0.93,4.1860,324.0,5.9248,0.0,1007.60,Foggy starting overnight continuing until morn...
65374,2013-07-22 22:00:00.000 +0200,Clear,rain,17.900000,17.900000,0.79,3.0751,220.0,15.8263,0.0,1015.00,Partly cloudy starting in the afternoon contin...
32055,2009-03-05 16:00:00.000 +0100,Breezy and Mostly Cloudy,rain,10.972222,10.972222,0.66,35.3073,137.0,10.3684,0.0,985.62,Mostly cloudy until night and breezy starting ...
20950,2008-01-28 22:00:00.000 +0100,Partly Cloudy,snow,-3.183333,-3.183333,0.76,2.5599,222.0,14.9569,0.0,1034.07,Breezy starting overnight continuing until mor...
41932,2010-11-02 05:00:00.000 +0100,Mostly Cloudy,rain,7.616667,5.438889,0.83,12.0106,138.0,9.9820,0.0,1015.68,Mostly cloudy throughout the day.

In [20]:
#renaming

data.rename(columns = {'Weather' : 'Weather info'})

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.
...,...,...,...,...,...,...,...,...,...,...,...,...
96448,2016-09-09 19:00:00.000 +0200,Partly Cloudy,rain,26.016667,26.016667,0.43,10.9963,31.0,16.1000,0.0,1014.36,Partly cloudy starting in the morning.
96449,2016-09-09 20:00:00.000 +0200,Partly Cloudy,rain,24.583333,24.583333,0.48,10.0947,20.0,15.5526,0.0,1015.16,Partly cloudy starting in the morning.
96450,2016-09-09 21:00:00.000 +0200,Partly Cloudy,rain,22.038889,22.038889,0.56,8.9838,30.0,16.1000,0.0,1015.66,Partly cloudy starting in the morning.
96451,2016-09-09 22:00:00.000 +0200,Partly Cloudy,rain,21.522222,21.522222,0.60,10.5294,20.0,16.1000,0.0,1015.95,Partly cloudy starting in the morning.
96452,2016-09-09 23:00:00.000 +0200,Partly Cloudy,rain,20.438889,20.438889,0.61,5.8765,39.0,15.5204,0.0,1016.16,Partly cloudy starting in the morning.

In [23]:
data.rename(columns = {'Loud Cover':'Cover'})

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.
...,...,...,...,...,...,...,...,...,...,...,...,...
96448,2016-09-09 19:00:00.000 +0200,Partly Cloudy,rain,26.016667,26.016667,0.43,10.9963,31.0,16.1000,0.0,1014.36,Partly cloudy starting in the morning.
96449,2016-09-09 20:00:00.000 +0200,Partly Cloudy,rain,24.583333,24.583333,0.48,10.0947,20.0,15.5526,0.0,1015.16,Partly cloudy starting in the morning.
96450,2016-09-09 21:00:00.000 +0200,Partly Cloudy,rain,22.038889,22.038889,0.56,8.9838,30.0,16.1000,0.0,1015.66,Partly cloudy starting in the morning.
96451,2016-09-09 22:00:00.000 +0200,Partly Cloudy,rain,21.522222,21.522222,0.60,10.5294,20.0,16.1000,0.0,1015.95,Partly cloudy starting in the morning.
96452,2016-09-09 23:00:00.000 +0200,Partly Cloudy,rain,20.438889,20.438889,0.61,5.8765,39.0,15.5204,0.0,1016.16,Partly cloudy starting in the morning.

In [24]:
data.Humidity.mean()

0.7348989663358906

In [25]:
data.Humidity.std()

0.19547273906722662

In [26]:
data.Precip Type.std()

SyntaxError: invalid syntax (<ipython-input-26-b52e29b7876f>, line 1)

In [27]:
data['Precip Type'].std()

TypeError: could not convert string to float: 'rain'

In [28]:
data.Apparent Temperature (C).std()

SyntaxError: invalid syntax (<ipython-input-28-b1e336036693>, line 1)

In [29]:

#small obseration for columns names with space use squ braces, for normal use parentheis
data['Apparent Temperature (C)'].std()

10.696847392119263

In [31]:
data['Precip Type'].value_counts()

rain    85224
snow    10712
Name: Precip Type, dtype: int64

In [32]:
data[data['Precip Type'] == 'snow']#filtering

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
1562,2006-12-13 02:00:00.000 +0100,Foggy,snow,-0.483333,-4.150000,1.00,11.0929,219.0,0.4830,0.0,1031.56,Foggy throughout the day.
1563,2006-12-13 03:00:00.000 +0100,Foggy,snow,-0.483333,-4.061111,0.96,10.7387,200.0,0.3220,0.0,1031.47,Foggy throughout the day.
1564,2006-12-13 04:00:00.000 +0100,Foggy,snow,-0.922222,-3.477778,1.00,7.0679,206.0,0.1610,0.0,1031.23,Foggy throughout the day.
1565,2006-12-13 05:00:00.000 +0100,Foggy,snow,-1.038889,-4.400000,1.00,9.4990,199.0,0.1610,0.0,1031.41,Foggy throughout the day.
1566,2006-12-13 06:00:00.000 +0100,Foggy,snow,-1.088889,-4.438889,1.00,9.4346,219.0,0.3220,0.0,1031.98,Foggy throughout the day.
...,...,...,...,...,...,...,...,...,...,...,...,...
93265,2016-03-28 05:00:00.000 +0200,Foggy,snow,-0.783333,-2.950000,0.99,6.1019,91.0,3.1073,0.0,1016.30,Foggy in the morning.
93266,2016-03-28 06:00:00.000 +0200,Foggy,snow,-1.111111,-1.111111,0.93,0.0000,0.0,0.1610,0.0,1016.41,Foggy in the morning.
93267,2016-03-28 07:00:00.000 +0200,Foggy,snow,-1.044444,-1.044444,1.00,0.0000,0.0,0.7728,0.0,1016.60,Foggy in the morning.
93311,2016-03-03 03:00:00.000 +0100,Partly Cloudy,snow,-0.511111,-0.511111,1.00,3.5098,74.0,14.6832,0.0,1004.57,Mostly cloudy throughout the day.
93506,2016-03-09 06:00:00.000 +0100,Foggy,snow,-0.027778,-2.705556,0.99,7.8568,320.0,3.0107,0.0,1014.76,Foggy in the morning.

In [33]:
#str.contaim
data[data['Precip Type'].str.contains('snow')]

ValueError: Cannot mask with non-boolean array containing NA / NaN values

In [34]:
#masking on;y done for true and false values only not NAN
data.head(2)

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.

In [35]:
data[data['Summary'].str.contains('Partly Cloudy')]

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
5,2006-04-01 05:00:00.000 +0200,Partly Cloudy,rain,9.222222,7.111111,0.85,13.9587,258.0,14.9569,0.0,1016.66,Partly cloudy throughout the day.
6,2006-04-01 06:00:00.000 +0200,Partly Cloudy,rain,7.733333,5.522222,0.95,12.3648,259.0,9.9820,0.0,1016.72,Partly cloudy throughout the day.
...,...,...,...,...,...,...,...,...,...,...,...,...
96448,2016-09-09 19:00:00.000 +0200,Partly Cloudy,rain,26.016667,26.016667,0.43,10.9963,31.0,16.1000,0.0,1014.36,Partly cloudy starting in the morning.
96449,2016-09-09 20:00:00.000 +0200,Partly Cloudy,rain,24.583333,24.583333,0.48,10.0947,20.0,15.5526,0.0,1015.16,Partly cloudy starting in the morning.
96450,2016-09-09 21:00:00.000 +0200,Partly Cloudy,rain,22.038889,22.038889,0.56,8.9838,30.0,16.1000,0.0,1015.66,Partly cloudy starting in the morning.
96451,2016-09-09 22:00:00.000 +0200,Partly Cloudy,rain,21.522222,21.522222,0.60,10.5294,20.0,16.1000,0.0,1015.95,Partly cloudy starting in the morning.
96452,2016-09-09 23:00:00.000 +0200,Partly Cloudy,rain,20.438889,20.438889,0.61,5.8765,39.0,15.5204,0.0,1016.16,Partly cloudy starting in the morning.

In [36]:
#and operator

data.head(2)

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.

In [38]:
data[(data['Precip Type']== 'rain') &  (data['Pressure (millibars)'] >1015.13)]

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.
5,2006-04-01 05:00:00.000 +0200,Partly Cloudy,rain,9.222222,7.111111,0.85,13.9587,258.0,14.9569,0.0,1016.66,Partly cloudy throughout the day.
...,...,...,...,...,...,...,...,...,...,...,...,...
96441,2016-09-09 12:00:00.000 +0200,Partly Cloudy,rain,28.866667,28.216667,0.37,13.9265,61.0,16.1000,0.0,1015.35,Partly cloudy starting in the morning.
96449,2016-09-09 20:00:00.000 +0200,Partly Cloudy,rain,24.583333,24.583333,0.48,10.0947,20.0,15.5526,0.0,1015.16,Partly cloudy starting in the morning.
96450,2016-09-09 21:00:00.000 +0200,Partly Cloudy,rain,22.038889,22.038889,0.56,8.9838,30.0,16.1000,0.0,1015.66,Partly cloudy starting in the morning.
96451,2016-09-09 22:00:00.000 +0200,Partly Cloudy,rain,21.522222,21.522222,0.60,10.5294,20.0,16.1000,0.0,1015.95,Partly cloudy starting in the morning.
96452,2016-09-09 23:00:00.000 +0200,Partly Cloudy,rain,20.438889,20.438889,0.61,5.8765,39.0,15.5204,0.0,1016.16,Partly cloudy starting in the morning.

In [39]:
#meanvalues against tem

data.groupby('Temperature (C)').mean()

,Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars)
Temperature (C),,,,,,,
-21.822222,-21.822222,0.800000,3.075100,323.000000,1.368500,0.0,1033.660000
-21.111111,-21.111111,0.743333,3.756667,190.000000,2.146667,0.0,1033.400000
-20.783333,-20.783333,0.800000,4.427500,181.000000,1.787100,0.0,1032.330000
-20.555556,-23.238889,0.780000,4.830000,115.000000,2.737000,0.0,1032.950000
-20.277778,-25.072222,0.790000,5.667200,158.000000,1.803200,0.0,1033.530000
...,...,...,...,...,...,...,...
38.861111,37.327778,0.180000,17.388000,232.000000,9.982000,0.0,1009.890000
38.866667,37.950000,0.210000,12.751200,269.000000,9.982000,0.0,1011.000000
38.983333,36.962963,0.156667,12.354067,158.333333,9.982000,0.0,1012.536667
39.588889,37.600000,0.150000,12.203800,283.000000,10.352300,0.0,1010.240000
39.905556,37.538889,0.130000,23.586500,250.000000,9.982000,0.0,1007.550000

In [ ]:
#minand max values against temp
#min() and max(0 with group by)

#;